export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CLEAR_CART_ITEM = "CLEAR_CART_ITEM";

export const CART_ITEM_lOCAL_STORAGE = "CART_ITEM_lOCAL_STORAGE";